---
- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  package:
    name: "{{ system_packages }}"
    state: latest 

- name: Do not stop when lid closed
  lineinfile:
    dest: /etc/systemd/logind.conf
    regexp: "^#HandleLidSwitch=suspend"
    line: "HandleLidSwitch=ignore"
  notify: Restart Login deamon 
