---
- name: Ensure all groups are created
  group:
    name: "{{ item }}"
  loop:
    - docker
    - "{{ nonrootuser }}"

- name: Ensure the non-root user is created
  user: 
    name: "{{ nonrootuser }}"
    password: "{{password | password_hash('sha512')}}"
    groups:
      - sudo
      - docker
      - users
    append: yes
    shell: "{{ shell }}"

- name: Enable passwordless sudo for "{{username}}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{username}} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Suppress login message
  file:
    path: "/home/{{username}}/.hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
