---
- name: Stop Containers
  shell: docker-compose down
  args:
    chdir: /home/{{ username }}/{{ dev_repository }}

- name: Remove Existing Repository
  shell: rm -rf "{{ dev_repository }}"

- name: Clone Fresh Repository
  shell: git clone https://"{{ dev_repository_site }}""{{dev_repository_owner}}""{{dev_repository}}"
  notify: Build Fresh Docker

